### ISSUE TITLE
Auto import PrimeVue components

### ISSUE THREAD

**Issue by huzaifahj** [sfxcode/formkit-primevue#1]
Hey, this works great! FormKit and PrimeVue are a good match. The best of form development and UI.

Wondering if the app could bundle PrimeVue components somehow? So that we wouldn't have to do

```ts
import Calendar from "primevue/calendar"
app.component("Calendar", Calendar)
```

for each component we plan to use.

**Comment by ohmree** [comment]
@huzaifahj this should be possible using [`unplugin-vue-components`](https://github.com/antfu/unplugin-vue-components/), no?

**Comment by sfxcode** [comment]
Added Nuxt 3 Module

https://github.com/sfxcode/nuxt-primevue

Global PrimeVue Import and Formkit PrimeVue ...
