### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by csakis** [sfxcode/formkit-primevue#11]
Would it be possible to add `primeRadioButton` to the components?

**Comment by sfxcode** [comment]
Added first implementation in Version 1.1.4. . Some more styling is needed in json attributes. Example:

https://formkit-primevue.netlify.app/demo/radioButton

**Comment by csakis** [comment]
It looks like that the version on npmjs does not have the latest changes:
https://www.npmjs.com/package/@sfxcode/formkit-primevue?activeTab=code

**Comment by csakis** [comment]
Thank you!
