### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by web-fu** [sfxcode/formkit-primevue#13]
I'm trying to add primevue to formkit using this library by I get an error running after install:
"failed to resolve package @sfxcode/formkit-primevue" maybe it is related to this:
https://github.com/sfxcode/formkit-primevue/issues/4
I'm running vite with this config:

```
import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        vue(),
    ],
})
```

**Comment by sfxcode** [comment]
Can not reproduce

Maybe take a look at https://github.com/sfxcode/vite-primevue-starter
