### ISSUE TITLE
ToggleButton component problem

### ISSUE THREAD

**Issue by csakis** [sfxcode/formkit-primevue#14]
I am trying to customize the ToggleButton element.
I can use the `onLabel` and the `offLabel` attributes just fine. However, the `onClass` and `offClass` attributes do not work.

**Comment by sfxcode** [comment]
Hi, as far as i know ToggleButton does not support the onClass and offClass ...

**Comment by csakis** [comment]
Yes. I know, but the primeToggleButton component still "supports" those attributes in this repo. 
I managed to solve my problem with a pass-through setting for the PrimeVue toggle button.

**Comment by sfxcode** [comment]
Not in the current Version:

``` <ToggleButton
      v-model="context._value"
      :input-id="context.id"
      :disabled="attrs._disabled ?? false"
      :readonly="attrs._readonly ?? false"
      :input-style="attrs.style"
      :input-class="styleClass"
      :tabindex="attrs.tabindex"
      :aria-label="attrs.ariaLabel"
      :aria-labelledby="attrs.ariaLabelledby"
      :on-label="attrs.onLabel ?? 'Yes'"
      :off-label="attrs.offLabel ?? 'No'"
      :on-icon="attrs.onIcon ?? 'pi pi-check'"
      :off-icon="attrs.offIcon ?? 'pi pi-times'"
      :icon-pos="attrs.iconPos ?? 'left'"
      :pt="attrs.pt"
      :pt-options="attrs.ptOptions"
      :unstyled="attrs.unstyled ?? false"
      @change="handleChange"
    />
```

Should i close ?

Greetings,

Tom

**Comment by csakis-parsons** [comment]
Sorry for the late response.
