### ISSUE TITLE
CSS doesn't seem to work.

### ISSUE THREAD

**Issue by mynameisjeffe** [sfxcode/formkit-primevue#17]
Problem: CSS doesn't seem to properly inject
[Minimal code 
](https://stackblitz.com/edit/nuxt-starter-kcjz47?file=pages%2Findex.vue )

![image](https://github.com/sfxcode/formkit-primevue/assets/24786602/3427366d-4b6d-4e66-85a8-48b88b9ac420)
![image](https://github.com/sfxcode/formkit-primevue/assets/24786602/cf7e94e0-265b-4d90-a363-341f0b57dbcf)

As an aside, I also added a generic css on input 
```
input {
  width: 100%;
}
```

But it seems like it can't target Formik inputText

![image](https://github.com/sfxcode/formkit-primevue/assets/24786602/fc113ce5-0c86-48a6-9893-5ee41750003b)

kindly advice

**Comment by sfxcode** [comment]
Hi,

with the last version 1.4.1 most inputs are set to use width of 100% and should now work as expected.

Please give it a try and tell me if it works now.

Greetings,

Tom

**Comment by mynameisjeffe** [comment]
Hi Tom,

Thanks for this. I can confirm that primeInputText does indeed have 100%

But supposed I need to add css to customize the fields, how do I do it?

I tried to add
![image](https://github.com/sfxcode/formkit-primevue/assets/24786602/58bad1e4-d6fa-43ed-89c3-f914f23f8ca9)

![image](https://github.com/sfxcode/formkit-primevue/assets/24786602/ef3c2d9b-86d5-44d0-a0b1-86263bc85761)

But the css doesn't seem to reflect.
[
minimal reproduction](
https://stackblitz.com/edit/nuxt-starter-5fakm8?file=package.json,nuxt.config.ts,pages%2Findex.vue)

Best,
Jeff

**Comment by sfxcode** [comment]
I have checkout your sample, firs
Hi Jeff,

I have looked into your sample code. Your problem is first of all the scoped attribute in your style section. customClass is not available in the child components.

After removing it should work as expected.



```
<style lang="scss">

.p-formkit {
  .customClass {
    width: 50% !important;
    border: 2px solid red;
  }
}
</style>
```

If you only want fields to have smaller inputs the better way is using a div with a smaller width around your FormKit Tag.

Tell me if it helps ...

Greetings,

Tom

P.S.: Also unocss dependency and config  was missing and i had to add a .npmrc file with

```
shamefully-hoist=true
strict-peer-dependencies=false
```

to reduce dependencies ...

```
  "devDependencies": {
    "@iconify-json/carbon": "^1.1.21",
    "@iconify-json/mdi": "^1.1.54",
    "@iconify-json/prime": "^1.1.6",
    "@iconify-json/twemoji": "^1.1.12",
    "@sfxcode/nuxt-primevue": "^1.4.1",
    "@unocss/nuxt": "0.56.5",
    "nuxt": "^3.7.4",
    "sass": "^1.69.0"
  }
```

**Comment by mynameisjeffe** [comment]
Hi Tom,

This is greatly appreciated. Have checked the css is now making sense! 
Wrapping a div around FormKit Tag also works. Thank you for the advice.

Ah right, I totally forgot to add unocss/nuxt. Thank you for pointing that out too.

Closing the ticket!
