### ISSUE TITLE
formkit-prime-inputs.scss missing

### ISSUE THREAD

**Issue by csakis-parsons** [sfxcode/formkit-primevue#19]
Hi Tom!
It looks like the `formkit-prime-inputs.scss` file has been removed from v1.3.5 to 1.4.0, Is there a reason for that? This change breaks earlier setups.

**Comment by sfxcode** [comment]
Hi, sorry but i removed this file in the last version. I decided not to use a fixed width of 300px anymore and go with the PrimeVue Standard. After the Update formkit-prime-inputs.scss was no longer needed anymore.
Please remove the usage of this file in your project and anything should work as expected.

Greetings,

Tom

**Comment by csakis-parsons** [comment]
dang, refactor coming!
