### ISSUE TITLE
Prime Input Validations don't quite respond the same way as FormKit defaults

### ISSUE THREAD

**Issue by JohnCampionJr** [sfxcode/formkit-primevue#2]
I think this is due to the missing blur handlers.  

[FormKit's docs](https://formkit.com/advanced/custom-inputs#input-checklist) say to handle both input and blur.

I've started working on fixes in my fork.  Will send PR if you're interested.

If you add some validation rules to the demo, it gets easier to see.

**Comment by sfxcode** [comment]
Hi, i will be glad if you like to participate with a merge request.

Thx for your very valuable input and greetinge,

Tom

**Comment by JohnCampionJr** [comment]
There will be a new PrimeVue release next week with the event added that will let me add a blur to the editor.

https://github.com/primefaces/primevue/issues/2829

Once that's out, I'll finish up and submit the PR.
