### ISSUE TITLE
dropdown does not highlight with red on error

### ISSUE THREAD

**Issue by Venkata-Adari** [sfxcode/formkit-primevue#20]
Dropdown does not have any .p-valid class to any of the dropdown formkit component.  p-dropdown tag should have an p-invalid class to add special treatment to satisfy requirements.

Version used:
"@sfxcode/formkit-primevue": "^1.3.4"
"nuxt": "^3.7.4",

Repro link:
https://formkit-primevue.netlify.app/demo/dropdown

**Comment by sfxcode** [comment]
You are right - dropdown is actual using class property and not input-class .

Wrong API description in the PrimeVue API documentation. Will fix this.
