### ISSUE TITLE
"primeCalendar" does not trigger error when validation: 'required" on blur

### ISSUE THREAD

**Issue by Venkata-Adari** [sfxcode/formkit-primevue#22]
"primeCalendar" does not trigger error on validation: 'required".

Version used:
"@sfxcode/formkit-primevue": "^1.3.4"
"nuxt": "^3.7.4",

{
    $formkit: "primeCalendar",
    name: "dob",
    label: "Date of Birth",
    validation: 'required',
    placeholder: 'MM/DD/YYYY'
}

Demo from formkit-primcevue - repro - please check primeCalendar:
https://formkit-primevue.netlify.app/demo/dropdown

**Comment by sfxcode** [comment]
Actual it does. Please check:

https://formkit-primevue.netlify.app/demo/calendar.

After submit it shows the required message as expected.

Greetings,

Tom

**Comment by Venkata-Adari** [comment]
You are correct, I was expecting a validation error on blur of dropdown.

**Comment by sfxcode** [comment]
fixed in 1.4.4
