### ISSUE TITLE
Error compiling version 1.4.4

### ISSUE THREAD

**Issue by smorcuend** [sfxcode/formkit-primevue#24]
Hi @sfxcode!
First of all, congratulations on your efforts to integrate formkit with primevue.
I notice that the latest version (1.4.4) has a bad build for distributable package.
When I install this version, the package does not resolve correctly and dist folder code doesn't appear.

``` 
ERROR  Failed to resolve entry for package "@sfxcode/formkit-primevue". The package may have incorrect main/module/exports specified in its package.json.
``` 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/tqXrMJs/Screenshot-from-2023-11-02-09-25-38.png" alt="Screenshot-from-2023-11-02-09-25-38" border="0"></a>

greetings

**Comment by sfxcode** [comment]
Hi,

thank you for pointing out. Fixed in the new 1.4.5 release.

Have a nice coding time,

Tom
