### ISSUE TITLE
How to use primevue events in the schema?

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [sfxcode/formkit-primevue#26]

**Comment by sfxcode** [comment]
Good morning,

at the moment events are only processed in the wrapped component like @input, @blur ...

Can you provide a small sample what event you need in a configuration based sample ?

imho most of them are not needed, but maybe there are some use cases, where it can be useful.

Please provide a litte more context ,

Greetings,

Tom

**Comment by sfxcode** [comment]
I will close this issue for now.
