### ISSUE TITLE
Auto imprt with "unplugin-auto-import"?

### ISSUE THREAD

**Issue by csakis** [sfxcode/formkit-primevue#32]
This is a feature request.
I love using the auto-import plugin in my new project. However, with the `formkit-primevue` plugin, if I want to use a checkbox, I have to import it manually in my `main.ts`.  Is there an already existing solution for this?

**Comment by sfxcode** [comment]
Hi,

this package has no focus on importing of components.  Used Components in Formkit should be available in your application.
In the demo PrimeVue inputs are imported as module.

Examples of auto-import can also be found in the primevue-nuxt module:

https://github.com/primefaces/primevue-nuxt-module

Hope that helps,

Tom
