### ISSUE TITLE
InputMask example?

### ISSUE THREAD

**Issue by lmc3s3f0r** [sfxcode/formkit-primevue#33]
Hi. I'm trying to see how to use primeInputMask in the demo playground (https://formkit-primevue.netlify.app/), but if I change anything there with the schema text editor, instead of updating the form, the schema is displayed as text.

Anyway, in my app, if I set a FormKitSchema like this

{
      $formkit: 'primeInputMask',
      type: 'text,
      name: "Phone",
      mask: '+1 (###) ###-####',
      validation: 'required',
      validationVisibility: 'live'
    }
    
I can see the mask in the input, but typing doesn't do anything.

Would anybody have an example of how to use primeInputMask?

**Comment by sfxcode** [comment]
Hi,

your mask format is not valid.

It should be: 

```
{
      $formkit: 'primeInputMask',
      name: 'phone',
      label: 'Phone',
      mask: '+1 (999) 999-9999',
      placeholder: '+1 (###) ###-####',
      validation: 'required',
      validationVisibility: 'live',
    },
```

I will add it as demo.

Greetings,

Tom

**Comment by lmc3s3f0r** [comment]
Thanks @sfxcode! This worked like a charm :)
