### ISSUE TITLE
Missing input disabled state, while submitting a form via XHR/Fetch request.

### ISSUE THREAD

**Issue by ddoebertin** [sfxcode/formkit-primevue#35]
Hi,
I have the issue that input fields don't get the attribute disabled while submitting a form via XHR/Fetch request.

Do I miss something or need to configure for this behavior?
Using a standard "Formkit Form" all fields are disabled while ajax submitting.
The submit handler is async.

I am using Formkit 1.5.9 and @sfxcode/formkit-primevue in V1.7.1.

Thanks for your help,
Daniel

**Comment by sfxcode** [comment]
Hi Daniel,

thank you for reporting this issue. It should be fixed with the version 1.7.3.

Can you check and close if everything works as expected ?

Greetings,

Tom

**Comment by ddoebertin** [comment]
Hey Tom,
Installing V1.7.4 solves this issue.
Thank you so much for fixing!
Best,
Daniel
