### ISSUE TITLE
PrimeRadioButton issue

### ISSUE THREAD

**Issue by csakis** [sfxcode/formkit-primevue#37]
Something is fishy with the radio buttons. 
There are two custom class fields: `options_class`  and `option_class`. 
As far as I can see `options_class` works as it is supposed to, however, `option_class` doesn't. It's not defined in the `FormKitPrimeRadioButtonProps`.
If I look at the RadioButtons Example website: https://formkit-primevue.netlify.app/inputs/radioButton,  the radiobuttons 
are rendered this way:
![image](https://github.com/sfxcode/formkit-primevue/assets/2583367/794fc0d3-4c76-400c-85b9-fb0dfb69d59a)

There's a div with an empty class and a div under it with `option_class` attribute. 
Is this intended behavior?

I am trying to have my radiobuttons in a row and align the labels and the buttons vertically centered with flex box, and I am not able to do it because of the wrapper div with  the empty class, I don;t know how to target that div to not have an empty class.

**Comment by sfxcode** [comment]
You are right - option_class was not rendered .... should be fixed in 1.9.3

Please check the latest version if it solves your problem.

Greetings,

Tom

**Comment by csakis** [comment]
@sfxcode Thank you for the quick fix.  It's getting better. I have also just noticed that you added the `p-formkit-radio-label` hard-coded class to the label component of the RadioButton. Was there any reason to do so? Also , it would be nice to be able to  possible to customize the label with custom classes.

**Comment by sfxcode** [comment]
Hi,

added new label_class property. Feel free to try it out together with latest input: InputOtp ;-)

Nice coding time,

Tom

**Comment by csakis** [comment]
Thank you
