### ISSUE TITLE
Bug: File '/node_modules/@sfxcode/formkit-primevue/dist/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by kswzr** [sfxcode/formkit-primevue#39]
Hello,

when running vue-tsc over our code base we get the following error:

```File '/app/node_modules/@sfxcode/formkit-primevue/dist/index.d.ts' is not a module.```

The file is imported as:

```js
import { primeInputs } from '@sfxcode/formkit-primevue';
```

**Comment by TraceGroupJ** [comment]
I have the same issue. Replicated with barebones new vite/vue project.

**Comment by sfxcode** [comment]
Hi @kswzr , @TraceGroupJ ,

can you test again the latest version 1.9.8 ?


Thx,

Tom

**Comment by TraceGroupJ** [comment]
Hi Tom, Thanks for quick response, 1.9.8 is building & running ok for me now on barebones vite project.
