### ISSUE TITLE
Config Types

### ISSUE THREAD

**Issue by JohnCampionJr** [sfxcode/formkit-primevue#4]
If I have formkit.config.ts (rather than js), I get a type error saying no types are available on 

```ts
import { primeInputs } from '@sfxcode/formkit-primevue'
```

**Comment by sfxcode** [comment]
Hi,
getting the same warning but it work in my projects even with a formkit.config.ts file.
e.g. nuxt-primevue.

Maybe i missed something in generating the code while building, but i have no clue at the moment.

Thank you for your input,

Tom

**Comment by sfxcode** [comment]
Added index.d.ts in build. Type errors should be fixed now.
