### ISSUE TITLE
primeEditor: passing 'formats' attribute through attrs property

### ISSUE THREAD

**Issue by davidcushing** [sfxcode/formkit-primevue#40]
I'm trying to pass an array of strings through to the underlaying Quill editor. 
From what I can see in the primeVue and Quill documentation, passing an array of strings will configure the formatting options in the toolbar. https://quilljs.com/docs/formats 
I'm not enjoying any success though. Am I doing something wrong?

```
                        <FormKit
                            id="longDescription"
                            v-model="longDescription"
                            type="primeEditor"
                            label="Long Description"
                            style="height: 110px"
                            attrs="{
                                formats: ['bold', 'color', 'italic', 'underline']
                            }"
                        />
```

Expected result:
The editor toolbar would only show the Bold, Color, Italic and Underline buttons.

Actual result:
All the default buttons are still shown in the toolbar.

Many thanks!

**Comment by sfxcode** [comment]
Hi, i tried a little bit but it is not working as expected. Formats seems to be not supported. If you need a highly configurable Editor, you should better use TipTap or something equal.

Sorry for no better response this time,

Tom

**Comment by davidcushing** [comment]
Hey Tom
No worries, thank you so much for looking into it. 
Keep up the great work!
D.
