### ISSUE TITLE
Declare prop types as described by FormKit docs

### ISSUE THREAD

**Issue by fermuch** [sfxcode/formkit-primevue#41]
Hello! Great project and I love how organized it is. Adding & using it was a breeze!

Would it be possible to add the types of each component to FormKit [as it is described in the docs](https://formkit.com/essentials/custom-inputs)?

**Comment by akkim2** [comment]
It seems this project cannot be used with FormKit/TypeScript until this is done, as the project will not build (unless strictly using schema)!

**Comment by sfxcode** [comment]
Hi, adding types is possible but not on the top of my list. If i have some spare time i will look into it. 

Meanwhile if someone is willing to help i am glad to integrate a pull request for that topic.

Stay tuned,

Tom

**Comment by Xeyos88** [comment]
I started using this library and it is really interesting and useful. When I tried to build, however I ended up with the problem reported in this issue.
I think typescript is almost a must now, I hope for a resolution.

**Comment by Xeyos88** [comment]
I suggest to install the vue-tsc dependency and try to fix the main errors (not dev or test) given by the command  
`vue-tsc --build --force`
This at least makes it possible to build applications that use this library as a dependency and require type checking

**Comment by Xeyos88** [comment]
Yes it works, now the build with typechek goes.
I had to apply a few tricks to readjust my code but it works

**Comment by sfxcode** [comment]
Hi,

base types for custom inputs / outputs are added. 

I will close this for now.

Greetings and thanks to everybody,

Tom
