### ISSUE TITLE
PrimeInputNumber autocomplete

### ISSUE THREAD

**Issue by DavidMWBP** [sfxcode/formkit-primevue#42]
Does this component support autocomplete functionality?

We're running into a problem with validation when we do the following steps:

1. For an input field set `$formkit` to `primeInputText`
2. Fill in and submit form
3. At some point we made the aforementioned field use `primeInputNumber` instead
4. Browser suggesting the autocomplete value when `$formkit` was set to `primeInputText`
5. Validation breaking for the field 

When setting `$formkit` to `number` the validation is working as intended.

It seems the default behavior for `primeInputNumber` is to not have autocomplete enabled in the first place (and I don't see a way to change this in the documentation) , is this observation correct?

Cheers

**Comment by sfxcode** [comment]
Hi, i can not reproduce this issue.

If it stays a major issue for you please let me know.

For now i will close it.

Greetings,

Tom
