### ISSUE TITLE
Injecting formkit invalid property to primevue component in unstyled mode

### ISSUE THREAD

**Issue by lmc3s3f0r** [sfxcode/formkit-primevue#51]
Hi! I'm using unstyled PrimeVue 4, and formkit-primevue for validation. 

PrimeVue components have an "invalid" property that you can set to true or false to enable some tailwind classes. I'd like to know if there is a way to connect it to FormKit's validation event, so I can set the PrimeVue to invalid instead of adding an extra border through the p-formkit class.

**Comment by sfxcode** [comment]
Hi,

i use now the invalid property of PrimeVue components as default.

Thank you for pointing out, because it is also the better pattern for the styled mode ...

Please give it a try and inform me if something is not working as expected.

Have a nice coding time,

Tom

**Comment by lmc3s3f0r** [comment]
Hi! Thanks. I'll have to wait a bit to test this new version though, as currently there's a bug in Vue 3.5.x that is making the @click event being ignored (weird bug that I'm surprised it's not fixed yet), and I see the new version has been updated to the latest 3.5.

I'll let you know as soon as possible.

Just to be sure: does this mean I don't need to do anything to make a FormKit element be marked as invalid?

On the other hand, I'm using unstyled mode. Would this work in my case or would I need to do any extra configuration?

Thanks a lot in advance for your hard work :)

**Comment by molul** [comment]
> Hi,
> 
> i use now the invalid property of PrimeVue components as default.
> 
> Thank you for pointing out, because it is also the better pattern for the styled mode ...
> 
> Please give it a try and inform me if something is not working as expected.
> 
> Have a nice coding time,
> 
> Tom
> 

I just remembered about this issue, sorry. I currently can't test it because I can't get primevue and formkit to work properly on unstyled mode. Once I have that working, I'll try if this is working.

**Comment by lmc3s3f0r** [comment]
After testing yesterday release (2.4.10), I confirm the invalid property is properly injected. Thanks a lot again :)
