### ISSUE TITLE
Problem with "fluid" property in InputText

### ISSUE THREAD

**Issue by lmc3s3f0r** [sfxcode/formkit-primevue#54]
When using "fluid", a PrimeVue component should fill the container's width and height. In my case, I'm using PrimeVue unstyled.

This, however, doesn't happen in InputText, because its "div" wrapper, unlike other components like InputNumber, DatePicker, Select or TextArea, is not getting the classes defined in the theme when props.fluid === true.

I'll try to elaborate. I've set my p-formkit class to be `"h-full min-h-[46px] bg-orange-400"`, and I've set "fluid" to "true" in all my PrimeVue components.

In that scenario, this is how an InputText looks:
![Screenshot from 2024-09-23 14-44-11](https://github.com/user-attachments/assets/2b229f3f-9d30-44cb-8d1c-5072fd08530b)

You can see that there's room to fill below the input (you can see the div.p-formkit orange background). That's because the wrapper doesn't contain the "size-full" that 

For comparison, here are some InputNumber components, which work fine:
![Screenshot from 2024-09-23 14-39-48](https://github.com/user-attachments/assets/b287311f-39ae-4a7c-b068-c939d3288427)

In this case, you can see that the <span> wrapper has the "size-full" applied.

Hope it helps. Thanks in advance :)

**Comment by sfxcode** [comment]
Hi, 
normally i  use the provided sass file for my styling and i try to fix styling issues there.
By default this styling takes all available space in a container element.

Keep in mind that a formkit component is wrapped in some divs if you use tailwind like classes.

You can use the outerClass Property in the schema file to access the most outer div. 
I use this pattern for my simple column usage.

For example:

https://formkit-primevue.netlify.app/styling/grid

Maybe this information will help to solve your problem, please let me know ...

Greetings,

Tom

**Comment by lmc3s3f0r** [comment]
Hi Tom! Thanks for your reply :)

Not trying to be a PITA, but all the other components' wrappers do get the "size-full" property when fluid is set to true. InputText would be the only PrimeVue component (at least from the ones I've been using so far) that doesn't appy "size-full" to the wrapper when used inside a FormKit.

Just for your consideration, that maybe the solution would be doing in InputText the same that is being done in the other components :)

**Comment by molul** [comment]
Will try tomorrow morning. Thanks very much :)

**Comment by lmc3s3f0r** [comment]
It works! Thank you very much :)
