### ISSUE TITLE
Could not resolve "quill"

### ISSUE THREAD

**Issue by raizdev** [sfxcode/formkit-primevue#55]
````
import { primeInputs } from '@sfxcode/formkit-primevue'

const config = {
  inputs: primeInputs
}

export default config
````

X [ERROR] Could not resolve "quill"

    node_modules/primevue/editor/index.mjs:78:13:
      78 │       import('quill').then(function (module) {
         ╵              ~~~~~~~

  You can mark the path "quill" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this
  failure at run-time instead of bundle-time.

14:07:56 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/primevue/editor/index.mjs:78:13: ERROR: Could not resolve "quill"
    at failureErrorWithLog (C:\Users\starr500\Desktop\projects\primevue-examples\vite-quickstart\node_modules\esbuild\lib\main.js:1472:15)
    at C:\Users\starr500\Desktop\projects\primevue-examples\vite-quickstart\node_modules\esbuild\lib\main.js:945:25
    at C:\Users\starr500\Desktop\projects\primevue-examples\vite-quickstart\node_modules\esbuild\lib\main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Xeyos88** [comment]
This error still seems to be present.
![image](https://github.com/user-attachments/assets/95be9e55-30a4-488c-9fb4-8c663992ad4c)

**Comment by raizdev** [comment]
Just install it with npm and add it it vite.config in optimizedeps

**Comment by sfxcode** [comment]
Quill is for now a direct dependency
