### ISSUE TITLE
DatePicker doesn't show "next month" button icon when used inside FormKit

### ISSUE THREAD

**Issue by lmc3s3f0r** [sfxcode/formkit-primevue#57]
Hi there! In my PrimeVue 4 unstyled project, I noticed that the "next month" button icon is not displayed.

This is a PrimeVue DatePicker component:
![Screenshot from 2024-09-26 08-15-19](https://github.com/user-attachments/assets/9061d1dc-72f9-4d98-92e7-e138d66b7c91)

And the html code for the "next month" button:
![Screenshot from 2024-09-26 08-19-48](https://github.com/user-attachments/assets/dc29f393-da80-4194-bad0-495c5fc43b37)

And this is the DatePicker inside a FormKit:
![Screenshot from 2024-09-26 08-15-33](https://github.com/user-attachments/assets/78957903-546f-47ad-bfe0-b626efa5095d)

And the html code:
![Screenshot from 2024-09-26 08-20-05](https://github.com/user-attachments/assets/aa1f905c-c223-443a-87b4-15cb09875bf0)

The "previous month" button icon works correctly.

I managed to workaround this by adding some css to the class ".p-datepicker-next-button .p-button-icon", but since these classes were removed in a recent update of yours (which was cool, as they shouldn't be displayed), it's happening again, so I thought it's time to report it :)

**Comment by sfxcode** [comment]
Hi,

removed defaults icons from date picker because maybe it causes problems in unstyled mode.

Please check if it works.

Greetings,

Tom

**Comment by lmc3s3f0r** [comment]
Worked like a charm. Thanks a lot, Tom :)
