### ISSUE TITLE
Submit missing styling

### ISSUE THREAD

**Issue by raizdev** [sfxcode/formkit-primevue#59]
![image](https://github.com/user-attachments/assets/fb305815-c2a5-4ab9-a99b-eb92e7c458f3)

My submit is missing styling. If I import <Button /> inside the component from primevue then the styling is back.

![image](https://github.com/user-attachments/assets/c384d7e7-ebce-4915-84cd-941b464811f3)

What I am doing wrong?

**Comment by sfxcode** [comment]
Hi,

button styling is not really part of this framework, but depends on your environment.

Styling is done by the FormKit Element:

```    <FormKit
      id="form"
      v-model="formData"
      :form-class="formClass"
      :actions-class="actionsClass"
      type="form"
      :submit-label="submitLabel"
      :submit-attrs="{
        inputClass,
      }"
      @submit="handleSave"
    >
```

If you use PrimeVue styled, inputClass should be like 

```p-button p-component```

to be shown.

In unstyled mode use TailWind like classes for the button.

tbh, your example makes it very hard to suggest a solution for your problem ;-)

Hope that helps,

Greetings Tom

**Comment by raizdev** [comment]
I forgot to add example, i use the p-component p-button

````
<template>
      <FormKit
          id="form"
          v-model="data"
          type="form"
          :submit-attrs="{
            inputClass: 'p-button p-component',
          }"
          @submit="submitHandler"
      >
            <FormKitSchema :schema="schema" :data="data" />
        </FormKit>
</template>
````

**Comment by sfxcode** [comment]
Hm, 

that works normally at expected because it is the same pattern i use in the playground. 
FormKit should render at least an unstyled button.
You should check the output html and maybe the console if something goes wrong.

Greetings, Tom

**Comment by raizdev** [comment]
> Hm,
> 
> that works normally at expected because it is the same pattern i use in the playground. FormKit should render at least an unstyled button. You should check the output html and maybe the console if something goes wrong.
> 
> Greetings, Tom

I have made an example on stackblitz
https://stackblitz.com/edit/vitejs-vite-meubb6

As you can see the button is not styled.
If you add <Button /> component inside App.vue formkit will be styled.

**Comment by sfxcode** [comment]
You are right, i will try include the PrimeVue Button in my provided FormKitDataEdit component  to ensure proper style rendering.

Thank you for reporting and a nice coding time,

Tom

**Comment by raizdev** [comment]
@sfxcode thanks for your commit!! it working by default now :)
