### ISSUE TITLE
FormKitSchema doesn't update data props

### ISSUE THREAD

**Issue by ironytr** [sfxcode/formkit-primevue#60]
```
<script setup lang="ts">
import { FormKitSchema } from '@formkit/vue'

useHead({
  title: "Katalog Özellikleri",
})
const schemaGroup = reactive(
  [
    {
      $el: 'h2',
      children: ['Özellik Grubu Oluştur']
    },

    {
      $formkit: 'primeInputText',
      name: 'name',
      label: 'Özellik İsmi',
      help: 'Oluşturacağınız özellik için isim giriniz',
      validation: 'required'

    },
  ]
)

const attributeGroupForm = ref({})

</script>


<template>
  <div class="card">
    <FormKit type="form" id="form" v-model="attributeGroupForm" class="w-full" :submit-attrs="{
        inputClass: 'p-button p-component',
        wrapperClass: 'w-full',
        outerClass: 'w-full'
      }" @submit="">
      <pre>{{attributeGroupForm}}</pre>
        <FormKitSchema :schema="schemaGroup" :data="attributeGroupForm"/>
      </FormKit>
  </div>
</template>

```

no model capturing the input data
![image](https://github.com/user-attachments/assets/9a4c4c7f-a4ac-4ab0-9620-0d9cd5c22357)

**Comment by sfxcode** [comment]
Hi,

for me it looks like you don't use input elements from this framework but the default FormKit input elements.

Hard to say what your problem is, maybe the default formkit inputs are not registered in your formkit config.

Greetings,

Tom

**Comment by ironytr** [comment]
> Hi,
> 
> for me it looks like you don't use input elements from this framework but the default FormKit input elements.
> 
> Normaly i prefer not to mix ...
> 
> Hard to say what your problem is, maybe the default formkit inputs are not registered in your formkit config.
> 
> Greetings,
> 
> Tom

Oh, sorry my bad. I have updated first comment for sample code, prime inputs  not working for schema too.

**Comment by sfxcode** [comment]
Hi, 

can you provide a more complete demo on stackblitz ?

Hard to tell what goes wrong in your app. Maybe some configuration is missing. 
Are there console messages ?

Greetings,

Tom
