### ISSUE TITLE
primeAutocomplete selectedValue

### ISSUE THREAD

**Issue by raizdev** [sfxcode/formkit-primevue#61]
first of all, really thank you for this amazing contribution.
I switched from vuestic to primevue with formkit and this is the best choice I ever decided, your effort is great!!

now i'm struggling with the following issue, maybe you can help or it isnt implemented yet.

Lets say i have a object with a user list which contains username, id, email etc.
When I select option it pass the complete object inside as a value in user_id.

It would be nice if there is option to only select the key and value in the option. 

![image](https://github.com/user-attachments/assets/927473f0-a8f1-4ef9-a290-3fc9142e3da2)

For instance:

````
{
  "slots": {},
  "user_id": 1
}
````

Code:
````
<script setup>
import { reactive, ref } from 'vue'

const list = [
    { id: '1', name: 'Test', value: '123'},
    { id: '2', name: 'Test 1', value: '1234'}
]

function search(query, key) {
  return list.filter(i => i[key].toLowerCase().includes(query.toLowerCase()))
}


const schema = reactive(
  [
    {
        $formkit: 'primeAutoComplete',
        id: 'basic',
        name: 'user_id',
        complete: (event) => search(event, 'name'),
        dropdown: true,
        label: 'User',
        optionLabel: 'name', 
        optionValue: 'id'
    }
  ],
)

const data = ref({})

async function submitHandler() {
  await new Promise(resolve => setTimeout(resolve, 1000))
}
</script>

<template>
  <div class="max-w-xl">
    <div class="myFormkit">
      <FormKit
        id="form"
        v-model="data"
        type="form"
        :submit-attrs="{
          inputClass: 'p-button p-component',
        }"
        @submit="submitHandler"
      >
        <FormKitSchema :schema="schema" :data="data" />
            <template #submit>
            </template>
      </FormKit>
    </div>
    <h4>Data</h4>
    <pre>{{ data }}</pre>
  </div>
</template>
````

**Comment by sfxcode** [comment]
Hi,

imho PrimeAutocomplete is not the best option in this case. You can use a list of object and an optionLabel for display (filter), but the value is always an object if selection exists in your list or the string otherwise. PrimeSelect will be better suited for your preferred output data.

Anyway, using options for a list of objects and select some object by optionLabel i will support in the next version.

```
    {
      $formkit: 'primeAutoComplete',
      id: 'basic',
      name: 'id',
      dropdown: true,
      label: 'Object Autocomplete Use [t]om',
      options: userList,
      optionLabel: 'name',
      optionValue: 'id',
    },
```

but you have to convert to required value (e.g. id) on save by yourself ...

Greetings,

Tom

**Comment by raizdev** [comment]
> Hi,
> 
> imho PrimeAutocomplete is not the best option in this case. You can use a list of object and an optionLabel for display (filter), but the value is always an object if selection exists in your list or the string otherwise. PrimeSelect will be better suited for your preferred output data.
> 
> Anyway, using options for a list of objects and select some object by optionLabel i will support in the next version.
> 
> ```
>     {
>       $formkit: 'primeAutoComplete',
>       id: 'basic',
>       name: 'id',
>       dropdown: true,
>       label: 'Object Autocomplete Use [t]om',
>       options: userList,
>       optionLabel: 'name',
>     },
> ```
> 
> but you have to convert to required value (e.g. id) on save by yourself ...
> 
> Greetings,
> 
> Tom

Get it.

I moved from Vuestic to Primevue. it was very simple to choose labels/value dynamicly for instance if you working with objects in object in options->list.

You could do something like

<Select
   :text-by="(event) => event.geo_code.name"
   :value-by="(event) => event.geo_code.id"
 />
 
 will look for a workaround :) thanks.

**Comment by raizdev** [comment]
Aaah. 

````
    { $formkit: 'primeSelect', name: 'geo_code', label: 'Geo Code', optionLabel: 'expand.geo_code.name', optionValue: 'expand.geo_code.id', pocketbase: { field: 'geo_code', collection: 'projects_geo_code', filter: { filter: `project ~ "${route.params.id}"`, expand: 'geo_code' } } },
    { $formkit: 'primeSelect', name: 'wb_o', label: 'WB-O', optionLabel: 'fullname', optionValue: 'id', pocketbase: { field: 'wb_o', collection: 'users' } }
])
````

this works. thank you so much!
