### ISSUE TITLE
Feature: add a prop to set the underlying input type

### ISSUE THREAD

**Issue by Brads3290** [sfxcode/formkit-primevue#67]
I've got a text input that will accept a password, so I want the underlying input to be `type=password`. With the PrimeVue component, you can just set `<InputText type="password" ...` and it's fine; but with FormKit we already use the `type` attribute with `type="primeInputText"`.

I propose adding an `input-type=...` prop to the components that might need it, and passing it's value directly down to the PrimeVue component.

I can make a PR for this. Just wanted to discuss first. Is there a different way to set the `type` of the input that I'm not considering?

**Comment by Brads3290** [comment]
Ok I just found `primePassword` and now I feel a bit silly..

But maybe it's worth making `input-type` anyway? There are other text-based input types such as `type="email"`, `type=tel`, etc. 

Of course we could just use FormKit validation to replace those, but maybe there are reasons (accessibility?) why people might want to set the HTML input type.

**Comment by sfxcode** [comment]
Hi,

thank you for your proposal. Just added a new inputType property to PrimeInputText.

Please give it a try,

Greetings,

Tom
