### ISSUE TITLE
PrimeCalendar previous icon is wrong

### ISSUE THREAD

**Issue by riccardogilli** [sfxcode/formkit-primevue#9]
[PrimeCalendar](https://github.com/sfxcode/formkit-primevue/blob/main/src/formkit/PrimeCalendar.vue) previous icon is wrong, it's a calendar but it should be a chevron left.
`:previous-icon="attrs.previousIcon ?? 'pi pi-calendar'"`
I think it should be:
`:previous-icon="attrs.previousIcon ?? 'pi pi-chevron-left'"`

**Comment by sfxcode** [comment]
Hi,

thank you for your valuable input. Fixed in the latest Version (1.0.3).

Greetings,

Tom
